### PR TITLE
Include standard-only projects directly in profile.

### LINKED ISSUE #27: Move all custom code to custom subdirectory
The line between custom module and feature is pretty blurred and I don't see a benefit to putting them in separate directories. Developers at least know where to look if there are in the same directory.

### LINKED ISSUE #28: Move standard modules directly into profile
The following custom modules are only used in the standard profile and could be moved into this repo to ease management of the code:

- sitenow_apps
- sitenow_footer
- sitenow_ownership
- sitenow_social_media
- sitenow_articles
- sitenow_core
- sitenow_entity_view_modes
- sitenow_events
- sitenow_featured_slider
- sitenow_forms
- sitenow_navigation
- sitenow_pages
- sitenow_people
- sitenow_seo

The benefit of this would be removing the need to tag a release of that repo and updating the make here. Saves a step and time.

Issues to consider: Some Custom Service sites could be using these modules, and keeping them in separate repos could make updating the code in those sites easier. Perhaps we identify what custom sites are using these modules (sitenow_people and sitenow_articles come to mind) and we could decide to keep those as separate repos.

### PR DESCRIPTION
**Pull request by richardbporter**
resolves #28, resolves #27 

I double checked each project for the latest code and made note of any outstanding issues on #28. Looks like the lab theme changes would need to be reflected in the profile.

I tested this locally on an existing site and surprisingly didn't have any registry issues. We could include a RR for good measure though.

### CODE REVIEW

**Comment by richardbporter** [comment]
I've reflected the changes here but I had to update the eventmachine gem to compile sass locally.

**Comment by richardbporter** [comment]
Added an RR for good measure. There is a feature branch off of develop that we can deploy to dev at any time. We can test sites there.

**Comment by richardbporter** [comment]
Added update hook 7108 from sitenow_core based on a diff of when this PR was opened and the latest commit to sitenow_core. I think that is the only difference.

**Comment by genjohnson** [comment]
I added commit #a33b839 to address [#57](https://github.com/ITS-UofIowa/sitenow_standard_profile/issues/57).

If this PR doesn't get released during the May update cycle, this change is also available is [#42 of the sitenow_standard_lab_theme](https://github.com/ITS-UofIowa/sitenow_standard_lab_theme/pull/42)

**Comment by richardbporter** [comment]
We should bump the version numbers up to 3.x to avoid re-running any update hooks.

**Pull request merged**
