### PR TITLE
Get imgAreaSelect from GitHub

### PR DESCRIPTION
**Pull request by genjohnson**

### CODE REVIEW

**Comment by brandonneil** [comment]
I think in order to use the version on github directly, we would need to patch manual crop to support the different file structure of the library, as shown here http://cgit.drupalcode.org/manualcrop/commit/?id=d6c449d

**Comment by brandonneil** [comment]
Related issue: https://github.com/ITS-UofIowa/sitenow_standard_profile/issues/23

**Comment by brandonneil** [comment]
Here is the version of manual crop we'll need to update as well https://www.drupal.org/project/manualcrop/releases/7.x-1.6

**Comment by richardbporter** [comment]
Too bad this module doesn't have a make file that Drush use recursion with...

I've updated the library to match the version on the custom profile and the module as well. I think this is good to go.

**Pull request merged**
