### PR TITLE
Private files install

### PR DESCRIPTION
**Pull request by adamdelaney**
Sets up the private files system in the install process.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@adamdelaney i checked out the branch (commented out the tag) and ran an ldu and lsp for a standard site new install.

- private file system path looked correct.
- created a new webform with a file upload component that had private file system on by default. public was still an option.
- default file types were images only.
- submitted form with files using both the public an private field options. the private worked as expected (access denied).
- webform subdirectory test also stored the file accordingly.

also ran updates on an existing standard site however it didn't have an existing webform with a file component. updates ran fine, the same bullet points as above.

**Comment by adamdelaney** [comment]
I had to resolve a merge conflict in sitenow_forms on the restrict_file_extensions branch against the 7.x-1.x branch. For some reason the 7.x-1.x branch already had a 7101 update hook so I had to increment the branch update hooks to 7102 and 7103.

**Comment by adamdelaney** [comment]
I was able to confirm that the schema selection was still being presented to the user when adding a file upload field. I added code to form_webform_component_edit_form_alter() and form_form_builder_field_configure_alter() to set the access to this field to false. I pushed this code to the sitenow_forms feature branch.

**Comment by adamdelaney** [comment]
I re-ran ldu and did a test and everything looks good to me now. No errors on updb and things appear to be working as expected.

**Comment by brandonneil** [comment]
Moved the update hook setting up the private file system from sitenow_forms to the install profile.

Also utilized the helper function that is provided for the installer in the update hook for consistency.

I tested this as well as the corresponding https://github.com/ITS-UofIowa/sitenow_forms/pull/2 by updating a current standard site and the private file system was setup correctly, as well as installing a new site with no issue.

**Pull request merged**
