### PR TITLE
Add cache busting strings to WYSIWYG

### PR DESCRIPTION
**Pull request by brandonneil**

### CODE REVIEW

**Comment by brandonneil** [comment]
See https://github.com/ITS-UofIowa/sitenow_custom_profile/issues/97 for rationale/testing from custom service

**Comment by richardbporter** [comment]
I don't know how to replicate this issue and test the patch. I give it a 👍

**Comment by brandonneil** [comment]
It's hard to replicate the issue at the moment

To test:

Look at a local site and find the CKEditor-related assets that load when editing a field with a WYSIWYG. Confirm that there is a cache-busting parameter on them that is not the same as the variable_get of css_js_query_string.

After checking out this branch in your system make file and running a `nile ldu`, confirm that these assets ow use the same value as css_js_query_string.

**Comment by richardbporter** [comment]
Yes, that seems to be the case.

**Pull request merged**
